# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from carla_msgs/CarlaEgoVehicleInfoWheel.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarlaEgoVehicleInfoWheel(genpy.Message):
  _md5sum = "73e85d22cc2145b0a4cf17f2e801c1dd"
  _type = "carla_msgs/CarlaEgoVehicleInfoWheel"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#
# Copyright (c) 2019 Intel Coporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#
float32 tire_friction
float32 damping_rate
float32 steer_angle
bool disable_steering
"""
  __slots__ = ['tire_friction','damping_rate','steer_angle','disable_steering']
  _slot_types = ['float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tire_friction,damping_rate,steer_angle,disable_steering

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarlaEgoVehicleInfoWheel, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.tire_friction is None:
        self.tire_friction = 0.
      if self.damping_rate is None:
        self.damping_rate = 0.
      if self.steer_angle is None:
        self.steer_angle = 0.
      if self.disable_steering is None:
        self.disable_steering = False
    else:
      self.tire_friction = 0.
      self.damping_rate = 0.
      self.steer_angle = 0.
      self.disable_steering = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fB().pack(_x.tire_friction, _x.damping_rate, _x.steer_angle, _x.disable_steering))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.tire_friction, _x.damping_rate, _x.steer_angle, _x.disable_steering,) = _get_struct_3fB().unpack(str[start:end])
      self.disable_steering = bool(self.disable_steering)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fB().pack(_x.tire_friction, _x.damping_rate, _x.steer_angle, _x.disable_steering))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.tire_friction, _x.damping_rate, _x.steer_angle, _x.disable_steering,) = _get_struct_3fB().unpack(str[start:end])
      self.disable_steering = bool(self.disable_steering)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fB = None
def _get_struct_3fB():
    global _struct_3fB
    if _struct_3fB is None:
        _struct_3fB = struct.Struct("<3fB")
    return _struct_3fB
