(cl:defpackage carla_msgs-msg
  (:use )
  (:export
   "<CARLACOLLISIONEVENT>"
   "CARLACOLLISIONEVENT"
   "<CARLAEGOVEHICLECONTROL>"
   "CARLAEGOVEHICLECONTROL"
   "<CARLAEGOVEHICLEINFO>"
   "CARLAEGOVEHICLEINFO"
   "<CARLAEGOVEHICLEINFOWHEEL>"
   "CARLAEGOVEHICLEINFOWHEEL"
   "<CARLAEGOVEHICLESTATUS>"
   "CARLAEGOVEHICLESTATUS"
   "<CARLALANEINVASIONEVENT>"
   "CARLALANEINVASIONEVENT"
   "<CARLAMAPINFO>"
   "CARLAMAPINFO"
  ))

